# Generated by Django 5.0.6 on 2024-06-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRegistrationModel",
            fields=[
                ("userid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, default="", max_length=100)),
                ("password", models.CharField(default="", max_length=100)),
            ],
            options={
                "verbose_name": "UserRegistration",
                "verbose_name_plural": "UserRegistrations",
            },
        ),
    ]
